# Generated by Django 5.2 on 2025-05-07 01:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_tester', '0002_server'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='completed', max_length=20)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_tester.profile')),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_tester.server')),
                ('target_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='target_test_runs', to='api_tester.profile')),
            ],
        ),
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_url', models.URLField()),
                ('request_method', models.CharField(max_length=10)),
                ('request_parameters', models.JSONField(default=dict)),
                ('response_status', models.IntegerField()),
                ('response_headers', models.JSONField(default=dict)),
                ('response_data', models.JSONField(null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('endpoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_tester.apiendpoint')),
                ('test_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='api_tester.testrun')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
