# Generated by Django 5.2 on 2025-05-08 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_tester', '0003_testrun_testresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='testresult',
            name='test_type',
            field=models.CharField(choices=[('normal', 'Normal Test'), ('target_params', 'Target Profile Parameters Test')], default='normal', max_length=20),
        ),
    ]
